name: Hello World!

on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Say Hello
        run: |
          echo "Hello, world!"
      - name: Show date
        run: |
          date
      - name: Show current directory
        run: |
          ls -l
